version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  version: 2
  commit:
    jobs:
      - cypress/run:
          record: true
  nightly:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - cypress/run:
          record: true